### ISSUE TITLE
Can Lamma be compiled as 'Pure' Scala for ScalaJS?

### ISSUE THREAD

**Issue by sixman9** [maxcellent/lamma#10]
OK, I haven't tried this but I looking for a non-Java (Scala-Only) date library, to embed in ScalaJS. 

Is Lamma dependent on its Java code when executed in a Scala-only environment?

**Comment by maxcellent** [comment]
I have reached out Sébastien from Scala JS, and checked this page: http://stackoverflow.com/questions/30143126/how-do-i-port-an-existing-scala-library-to-scalajs

It requires major refactoring to cross compile the library onto different platform. Maybe it will be a major one for 3.0.

**Comment by sixman9** [comment]
Max,
Does the [runtime] **Scala** code within Lamma use either:

1. external Java library dependencies (libs/JARs etc)?
2. compiles against **\*.java** source files, e.g. under '**/src/main/java/...**', for example?
3. Networking (unlikely, but asked anyway)? 

If Lamma's [runtime] **Scala** code requires ***no*** Java dependencies, then your *Scala* code* should run within the ScalaJS environment, as far as I am aware.

Can you confirm or dismiss the above points regarding the Lamma project?

\* Java-based tests would not convert to ScalaJS, which is reasonable/OK

**Comment by maxcellent** [comment]
1. external Java library dependencies (libs/JARs etc)?
    No. It only depends on 
2. compiles against *.java source files, e.g. under '/src/main/java/...', for example?
    Yes but most of them are only used for java interface, which is not needed for scalajs. Another small java dependency is java enum, which can be replaced by Scala equivalent. That's why I said it requires some refactoring.
3. Networking (unlikely, but asked anyway)?
    No

**Comment by ngbinh** [comment]
there are works on scala.js to bring `j.u.time` and `j.u.date` to scala.js libraries. Not sure if it helps?

**Comment by maxcellent** [comment]
Do you mind to share the link with the full list of supported JDK classes?

Apart from that, we are also using java.util.Timezone and
java.util.Calendar as well.

**Comment by maxcellent** [comment]
feel free to reopen if you have more findings
