### ISSUE TITLE
How to compute my schedule based on number of occurrences and no end date

### ISSUE THREAD

**Issue by rv264** [maxcellent/lamma#13]
How to compute my schedule based on number of occurrences and no end date? For example, my event starts today every day for the next 10 occurrences ( no end date specified).

How to build this pattern and get all the dates for this use case? 

Appreciate your help.

**Comment by maxcellent** [comment]
not very clean but works. hope it helps:

```
scala> import io.lamma.Date
val from = Date.today()
val to = from + 10 * 10
from until to by 10 foreach println
import io.lamma.Date

scala> from: io.lamma.Date = Date(2017,9,2)

scala> to: io.lamma.Date = Date(2017,12,11)

scala> Date(2017,9,2)
Date(2017,9,12)
Date(2017,9,22)
Date(2017,10,2)
Date(2017,10,12)
Date(2017,10,22)
Date(2017,11,1)
Date(2017,11,11)
Date(2017,11,21)
Date(2017,12,1)
```

**Comment by rv264** [comment]
Thank you very much


________________________________
