### ISSUE TITLE
Spring/JPA/Hibernate integration

### ISSUE THREAD

**Issue by igler** [maxcellent/lamma#5]
Can lamma be integrated into a Spring/JPA/Hibernate-environment? Currently I use mappings like this
<pre><code>@Type(type = "org.jadira.usertype.dateandtime.threeten.PersistentZonedDateTime")
private ZonedDateTime validFrom;
</code></pre>
to store JSR-310 ZonedDateTime in database.

**Comment by maxcellent** [comment]
Feel free to save lamma date as an ISO string. 32bits (single integer) representation will also be supported in the future version.

You should be able to easily define a custom type for Hibernate to persist lamma date: https://docs.jboss.org/hibernate/orm/3.6/reference/en-US/html/types.html#types-custom-type

For example,

```java
// from ISO string to date
Dates.newDate(isoString);

// from date to ISO string
Dates.newDate(2000, 5, 5).toISOString();
```
