### ISSUE TITLE
Joda-time's Date compatibility 

### ISSUE THREAD

**Issue by bmkmanoj** [maxcellent/lamma#6]
I have one concern - as an existing joda time user, I would have loved to see a "joda compatible Date" part of the API itself (like [google-rfc-2445](https://code.google.com/p/google-rfc-2445/) does). Right now if i use this to get recurrence pattern and feed it to my code which uses Joda, I have to do this manually.

Will it be possible to include the Joda Date support inbuilt to the API? If not, you may include some documentation mentioning the best practice inter conversion of lamma Date to Joda Date. (This would also make existing users of joda get started with lamma)

**Comment by maxcellent** [comment]
What is your use case? It's quite simple to convert the generated result into joda date. 

```scala
scala> import io.lamma._
import io.lamma._

scala> import org.joda.time.LocalDate
import org.joda.time.LocalDate

scala> (2015, 1, 5) to (2015, 1, 10) map {d => new LocalDate(d.yyyy, d.mm, d.dd)} 
res0: scala.collection.immutable.IndexedSeq[org.joda.time.LocalDate] = Vector(2015-01-05, 2015-01-06, 2015-01-07, 2015-01-08, 2015-01-09, 2015-01-10)
```
